// Code generated by "stringer -type=TNSType"; DO NOT EDIT.

package go_ora

import (
	//"strconv"

	oraTypes "github.com/sijms/go-ora/v3/types"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[oraTypes.NCHAR-1]
	_ = x[oraTypes.NUMBER-2]
	_ = x[oraTypes.BInteger-3]
	_ = x[oraTypes.FLOAT-4]
	_ = x[oraTypes.NullStr-5]
	_ = x[oraTypes.VarNum-6]
	_ = x[oraTypes.LONG-8]
	_ = x[oraTypes.VARCHAR-9]
	_ = x[oraTypes.ROWID-11]
	_ = x[oraTypes.DATE-12]
	_ = x[oraTypes.VarRaw-15]
	_ = x[oraTypes.BFLOAT-21]
	_ = x[oraTypes.BDOUBLE-22]
	_ = x[oraTypes.RAW-23]
	_ = x[oraTypes.LongRaw-24]
	_ = x[oraTypes.UINT-68]
	_ = x[oraTypes.LongVarChar-94]
	_ = x[oraTypes.LongVarRaw-95]
	_ = x[oraTypes.CHAR-96]
	_ = x[oraTypes.CHARZ-97]
	_ = x[oraTypes.IBFLOAT-100]
	_ = x[oraTypes.IBDOUBLE-101]
	_ = x[oraTypes.REFCURSOR-102]
	_ = x[oraTypes.OCIXMLType-108]
	_ = x[oraTypes.XMLType-109]
	_ = x[oraTypes.OCIRef-110]
	_ = x[oraTypes.OCIClobLocator-112]
	_ = x[oraTypes.OCIBlobLocator-113]
	_ = x[oraTypes.OCIFileLocator-114]
	_ = x[oraTypes.RESULTSET-116]
	_ = x[oraTypes.OCIString-155]
	_ = x[oraTypes.OCIDate-156]
	_ = x[oraTypes.TimeStampDTY-180]
	_ = x[oraTypes.TimeStampTZ_DTY-181]
	_ = x[oraTypes.INTERVALYM_DTY-182]
	_ = x[oraTypes.INTERVALDS_DTY-183]
	_ = x[oraTypes.TimeTZ-186]
	_ = x[oraTypes.TIMESTAMP-187]
	_ = x[oraTypes.TIMESTAMPTZ-188]
	_ = x[oraTypes.IntervalYM-189]
	_ = x[oraTypes.IntervalDS-190]
	_ = x[oraTypes.UROWID-208]
	_ = x[oraTypes.TimeStampLTZ_DTY-231]
	_ = x[oraTypes.TimeStampeLTZ-232]
}

const _OracleType_name = "NCHARNUMBERSB1FLOATNullStrVarNumLONGVARCHARROWIDDATEVarRawBFloatBDoubleRAWLongRawUINTLongVarCharLongVarRawCHARCHARZIBFloatIBDoubleREFCURSOROCIXMLTypeXMLTypeOCIRefOCIClobLocatorOCIBlobLocatorOCIFileLocatorResultSetOCIStringOCIDateTimeStampDTYTimeStampTZ_DTYIntervalYM_DTYIntervalDS_DTYTimeTZTIMESTAMPTimeStampTZIntervalYMIntervalDSUROWIDTimeStampLTZ_DTYTimeStampeLTZ"

var _OracleType_map = map[uint16]string{
	1:   _OracleType_name[0:5],
	2:   _OracleType_name[5:11],
	3:   _OracleType_name[11:14],
	4:   _OracleType_name[14:19],
	5:   _OracleType_name[19:26],
	6:   _OracleType_name[26:32],
	8:   _OracleType_name[32:36],
	9:   _OracleType_name[36:43],
	11:  _OracleType_name[43:48],
	12:  _OracleType_name[48:52],
	15:  _OracleType_name[52:58],
	21:  _OracleType_name[58:64],
	22:  _OracleType_name[64:71],
	23:  _OracleType_name[71:74],
	24:  _OracleType_name[74:81],
	68:  _OracleType_name[81:85],
	94:  _OracleType_name[85:96],
	95:  _OracleType_name[96:106],
	96:  _OracleType_name[106:110],
	97:  _OracleType_name[110:115],
	100: _OracleType_name[115:122],
	101: _OracleType_name[122:130],
	102: _OracleType_name[130:139],
	108: _OracleType_name[139:149],
	109: _OracleType_name[149:156],
	110: _OracleType_name[156:162],
	112: _OracleType_name[162:176],
	113: _OracleType_name[176:190],
	114: _OracleType_name[190:204],
	116: _OracleType_name[204:213],
	155: _OracleType_name[213:222],
	156: _OracleType_name[222:229],
	180: _OracleType_name[229:241],
	181: _OracleType_name[241:256],
	182: _OracleType_name[256:270],
	183: _OracleType_name[270:284],
	186: _OracleType_name[284:290],
	187: _OracleType_name[290:299],
	188: _OracleType_name[299:310],
	189: _OracleType_name[310:320],
	190: _OracleType_name[320:330],
	208: _OracleType_name[330:336],
	231: _OracleType_name[336:352],
	232: _OracleType_name[352:365],
}
//
//func (i uint16) String() string {
//	if str, ok := _OracleType_map[i]; ok {
//		return str
//	}
//	return "TNSType(" + strconv.FormatInt(int64(i), 10) + ")"
//}
